version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=sqs,dynamodb,s3
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=ap-southeast-1
      - DEBUG=1
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - "./localstack:/var/lib/localstack"
    healthcheck:
      test: "curl -f http://localhost:4566/_localstack/health || exit 1"
      interval: 30s
      timeout: 20s
      retries: 3

  sqs-setup:
    image: amazon/aws-cli:latest
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_DEFAULT_REGION=ap-southeast-1
    entrypoint: >
      /bin/sh -c "
      sleep 10 &&
      aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name hub-data-queue-local &&
      aws --endpoint-url=http://localstack:4566 dynamodb create-table --table-name wt_cache_local --attribute-definitions AttributeName=ID,AttributeType=S --key-schema AttributeName=ID,KeyType=HASH --billing-mode PAY_PER_REQUEST
      "
